locals {
  # Order matters: last match wins in CODEOWNERS.
  # Catch-all first, then increasingly specific patterns.
  standard_codeowners_lines = [
    "* @${var.gh_org_name}/${var.infrastructure_approvers}",
    "environments/*/releases.auto.tfvars @${var.gh_org_name}/${var.release_managers}",
    ".github/workflows/** @${var.gh_org_name}/${var.pipeline_guardians}",
  ]

  extra_codeowners_lines = [
    for path, slug in var.extra_codeowners :
    "${path} @${var.gh_org_name}/${slug}"
  ]

  codeowners_content = join("\n", concat(
    local.standard_codeowners_lines,
    local.extra_codeowners_lines,
  ))
}

resource "github_repository_file" "codeowners" {
  count               = var.archived ? 0 : 1
  repository          = github_repository.this.name
  file                = ".github/CODEOWNERS"
  overwrite_on_create = true
  content = join("\n", [
    "# This file is managed by Terraform in github-control repository",
    "# Do not edit this file, all changes will be overwritten",
    "",
    local.codeowners_content,
    "",
  ])
  commit_message = "Update CODEOWNERS"
  branch         = local.default_branch
}
